apiVersion: k3d.io/v1alpha5
kind: Simple
metadata:
  name: ${CLUSTER_NAME}

servers: 1
agents: 2

registries:
  config: |
    mirrors:
      "localhost:5000":
        endpoint:
          - "http://${CLUSTER_NAME}-registry:5000"

ports:
  - port: 8080:80
    nodeFilters:
      - loadbalancer

volumes:
  - volume: ${FLUENT_BIT_DIR}/sim-k8s-logs/var/log/containers:/var/log/containers:rw
    nodeFilters:
      - all
  - volume: ${FLUENT_BIT_DIR}/data/gc-logs:/gc-logs:rw
    nodeFilters:
      - all
  - volume: ${FLUENT_BIT_DIR}/dummy-machine-id:/etc/machine-id:rw
    nodeFilters:
      - all
  - volume: ${FLUENT_BIT_DIR}/logs:/fluent-bit/logs:rw
    nodeFilters:
      - all
options:
  k3s:
    extraArgs:
      - arg: "--flannel-backend=none"
        nodeFilters:
          - server:*
      - arg: "--disable-network-policy"
        nodeFilters:
          - server:*
      - arg: "--disable=traefik"
        nodeFilters:
          - server:*
