replicaCount: 1

image:
  repository: localhost:5000/gc-analysis
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080

resources: {}

nodeSelector: {}
tolerations: []
affinity: []

javaOpts: "-Xmx512m -Xms512m -XX:+UseZGC -Xlog:gc:file=/logs/gc.log:time,uptime"

volumes:
  logs:
    enabled: true
    mountPath: /logs
    useHostPath: true
    hostPath: /gc-logs

sidecar:
  fluentbit:
    enabled: true
    image: fluent/fluent-bit:2.2.0
    mountPath: /logs
    configMap: fluent-bit-config


app:
  name: gc-app1-jdk17