apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "gc-analysis.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "gc-analysis.name" . }}
    helm.sh/chart: {{ include "gc-analysis.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "gc-analysis.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "gc-analysis.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ include "gc-analysis.name" . }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8080
          env:
            - name: JAVA_TOOL_OPTIONS
              value: "{{ .Values.javaOpts }}"
          {{- if .Values.volumes.logs.enabled }}
          volumeMounts:
            - name: log-volume
              mountPath: {{ .Values.volumes.logs.mountPath }}
          {{- end }}
      {{- if .Values.volumes.logs.enabled }}
      volumes:
        - name: log-volume
          emptyDir: {}
      {{- end }}
