apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "gc-analysis.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "gc-analysis.name" . }}
    helm.sh/chart: {{ include "gc-analysis.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "gc-analysis.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "gc-analysis.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ include "gc-analysis.name" . }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8080
          env:
            - name: JAVA_TOOL_OPTIONS
              value: "{{ .Values.javaOpts }}"
          {{- if .Values.volumes.logs.enabled }}
          volumeMounts:
            - name: log-volume
              mountPath: {{ .Values.volumes.logs.mountPath }}
          {{- end }}

        {{- if .Values.sidecar.fluentbit.enabled }}
        - name: fluent-bit
          image: {{ .Values.sidecar.fluentbit.image }}
          args: ["-c", "/fluent-bit/etc/fluent-bit.conf"]
          volumeMounts:
            - name: log-volume
              mountPath: {{ .Values.sidecar.fluentbit.mountPath }}
            - name: fluent-bit-config
              mountPath: /fluent-bit/etc
        {{- end }}

      volumes:
        {{- if .Values.volumes.logs.enabled }}
        - name: log-volume
          {{- if .Values.volumes.logs.useHostPath }}
          hostPath:
            path: {{ .Values.volumes.logs.hostPath }}
            type: DirectoryOrCreate
          {{- else }}
          emptyDir: {}
          {{- end }}
        {{- end }}
        {{- if .Values.sidecar.fluentbit.enabled }}
        - name: fluent-bit-config
          configMap:
            name: {{ .Values.sidecar.fluentbit.configMap }}
        {{- end }}
