apiVersion: v1
kind: ConfigMap
metadata:
  name: fluent-bit-config
data:
  fluent-bit.conf: |
    [SERVICE]
        Flush        1
        Daemon       Off
        Log_Level    info

    [INPUT]
        Name        tail
        Path        /logs/gc.log
        Parser      docker
        Tag         gc-log

    [OUTPUT]
        Name        stdout
        Match       *
