apiVersion: v1
kind: Service
metadata:
  name: {{ include "gc-analysis.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "gc-analysis.name" . }}
    helm.sh/chart: {{ include "gc-analysis.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "gc-analysis.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
